### ISSUE TITLE
Fix your fucking bug!

### ISSUE THREAD

**Issue by Witchs-Cat** [GoodDamn/TraceView_JS#1]
add this to body tag:
 body onload="onLoad()" id="main"
        ondragstart="return false;"
        ondrop="return false;"
body

**Comment by Witchs-Cat** [comment]
`<body onload="onLoad()" id="main" ondragstart="return false;"
        ondrop="return false;">

    </body>`

**Comment by Witchs-Cat** [comment]
body onload="onLoad()" id="main"
       ondragstart="return false;"
        ondrop="return false;"

body

**Comment by GoodDamn** [comment]
Yep! Thanks!
